'use client';
import { useCallback, useEffect, useState } from 'react';
import { Profile, OnboardingState, RoadmapResult } from '@/lib/types';
import Header, { AppSection } from '@/components/Header';
import Welcome from '@/components/onboarding/Welcome'; import ProfileSetup from '@/components/onboarding/ProfileSetup'; import AcademicsAndTests from '@/components/onboarding/AcademicsAndTests'; import Preferences from '@/components/onboarding/Preferences';
import Step3Diagnose from '@/components/steps/Step3Diagnose'; import Step4Recommendations from '@/components/steps/Step4Recommendations'; import Step5Compare from '@/components/steps/Step5Compare'; import Step6Roadmap from '@/components/steps/Step6Roadmap';

const INITIAL_STATE: OnboardingState = { currentStep: 0, profile: {}, diagnoseResult: null, recommendations: null, selectedForComparison: [], roadmap: null, roadmapProgress: {}, essayAnswers: {} };

export default function OnboardingWizard() {
  const [state, setState] = useState<OnboardingState>(INITIAL_STATE); const [loaded, setLoaded] = useState(false); const [onboarded, setOnboarded] = useState(false); const [section, setSection] = useState<AppSection>('profile'); const [uniTab, setUniTab] = useState<'recommendations'|'compare'>('recommendations'); const [loading, setLoading] = useState(false);
  useEffect(() => { try { const saved = localStorage.getItem('admitpath_state'); if (saved) setState(JSON.parse(saved)); setOnboarded(Boolean(localStorage.getItem('activeUser') && saved)); } catch { /* use defaults */ } setLoaded(true); }, []);
  useEffect(() => { if (loaded) localStorage.setItem('admitpath_state', JSON.stringify(state)); }, [state, loaded]);
  const updateProfile = (updates: Partial<Profile>) => setState(prev => ({ ...prev, profile: { ...prev.profile, ...updates } }));
  const runDiagnose = useCallback(async () => { setLoading(true); try { const res = await fetch('/api/diagnose', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(state.profile) }); const data = await res.json(); if (data.diagnosis) { setState(prev => ({ ...prev, diagnoseResult: data.diagnosis })); return data.diagnosis; } } finally { setLoading(false); } }, [state.profile]);
  const runRecommend = useCallback(async (diagnosis = state.diagnoseResult) => { if (!diagnosis) return; setLoading(true); try { const res = await fetch('/api/recommend', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ profile: state.profile, diagnosis }) }); const data = await res.json(); if (data.recommendations) setState(prev => ({ ...prev, recommendations: data.recommendations })); } finally { setLoading(false); } }, [state.profile, state.diagnoseResult]);
  const navigate = async (next: AppSection) => { setSection(next); if (next === 'diagnose' && !state.diagnoseResult) await runDiagnose(); if (next === 'universities' && !state.recommendations) { const diagnosis = state.diagnoseResult ?? await runDiagnose(); await runRecommend(diagnosis); } };
  const completeOnboarding = () => { setOnboarded(true); setSection('diagnose'); void runDiagnose(); };
  const logout = () => { localStorage.removeItem('activeUser'); setOnboarded(false); setSection('profile'); };
  if (!loaded) return <div className="min-h-screen flex items-center justify-center"><div className="w-10 h-10 border-4 border-accent border-t-transparent rounded-full animate-spin" /></div>;
  if (!onboarded) return <Welcome hasProfile={Boolean(localStorage.getItem('admitpath_state'))} onContinue={() => setOnboarded(true)} onStart={(name) => { updateProfile({ name } as any); setOnboarded(true); setSection('profile'); }} />;
  const common: any = { profile: state.profile, onUpdateProfile: updateProfile, diagnoseResult: state.diagnoseResult, recommendations: state.recommendations, selectedForComparison: state.selectedForComparison, onToggleComparison: (id: string) => setState(prev => ({ ...prev, selectedForComparison: prev.selectedForComparison.includes(id) ? prev.selectedForComparison.filter(x => x !== id) : prev.selectedForComparison.length < 4 ? [...prev.selectedForComparison, id] : prev.selectedForComparison })), roadmap: state.roadmap, roadmapProgress: state.roadmapProgress, onToggleRoadmapItem: (id: string) => setState(prev => ({ ...prev, roadmapProgress: { ...prev.roadmapProgress, [id]: !prev.roadmapProgress[id] } })), onSetRoadmap: (roadmap: RoadmapResult) => setState(prev => ({ ...prev, roadmap })) };
  return <><Header section={section} onNavigate={navigate} onLogout={logout} /><main className="max-w-6xl mx-auto px-4 py-8">
    {section === 'profile' && <div className="space-y-8"><ProfileSetup profile={state.profile as any} onUpdate={updateProfile} onNext={() => undefined} /><AcademicsAndTests profile={state.profile} onUpdate={updateProfile} onNext={() => undefined} /><Preferences profile={state.profile} onUpdate={updateProfile} onComplete={completeOnboarding} /></div>}
    {section === 'diagnose' && <Step3Diagnose {...common} isLoadingDiagnose={loading} onNext={() => navigate('universities')} onBack={() => navigate('profile')} />}
    {section === 'universities' && <div className="space-y-5"><div className="flex gap-2"><button className={`chip ${uniTab === 'recommendations' ? 'chip-active' : ''}`} onClick={() => setUniTab('recommendations')}>Рекомендации</button><button className={`chip ${uniTab === 'compare' ? 'chip-active' : ''}`} onClick={() => setUniTab('compare')}>Сравнение</button></div>{uniTab === 'recommendations' ? <Step4Recommendations {...common} onNext={() => setUniTab('compare')} onBack={() => navigate('diagnose')} isLoadingRecommend={loading} /> : <Step5Compare {...common} onNext={() => navigate('roadmap')} onBack={() => setUniTab('recommendations')} />}</div>}
    {section === 'roadmap' && <Step6Roadmap {...common} onNext={() => undefined} onBack={() => navigate('universities')} />}
  </main></>;
}
